name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'  # runs daily at 04:30 UTC
  workflow_dispatch:        # optional: allows manual run

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with write token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit for 23f1001029@ds.study.iitm.ac.in
        run: |
          echo "Commit run at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update on $(date -u)" || echo "⚠️ Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
